### ISSUE TITLE
Simple mistake

### ISSUE THREAD

**Issue by TheMerkyShadow** [angelXwind/AppSync#10]
In the cydia installation panel it says supports 5.0 through 8.1. 
Should be (8.4) or 8.x.x.
I think you just overlooked it.
But other than that it's perfect!

**Comment by angelXwind** [comment]
The depiction reads: "Unified AppSync dynamic library for iOS 5, 6, 7, and 8. Supports arm64."

See: https://cydia.angelxwind.net/?page/net.angelxwind.appsyncunified

**Comment by TheMerkyShadow** [comment]
Um. Lol U Didn't Read My Comment...
This Picture Says It All...

http://www.mediafire.com/view/b44w5qsem1z9817

**Comment by TheMerkyShadow** [comment]
Low quality but I did this today...and it doesn't match ur description.

**Comment by angelXwind** [comment]
Oh, the postinst message. Didn't know what you meant by "installation panel" and had thought you had meant the depiction view instead :P

I'll fix that in a bit, along with something else saurik pointed out (unloading of installd as opposed to just stopping it)

**Comment by TheMerkyShadow** [comment]
Np I'm glad to help, just felt it looked unprofessional looking.
