### ISSUE TITLE
8.4越狱无法覆盖安装测试版app

### ISSUE THREAD

**Issue by cnhbxz** [angelXwind/AppSync#11]
非企业证书的 测试版的app无法覆盖安装  比如说QQ 提示更新测试版 点更新  无反应 如果卸载qq重启手机 在浏览器直接打开itms-services协议的安装地址 是可以全新安装的  这个问题只在8.4越狱中存在 是否是appsync的问题 还是太极越狱的问题？

**Comment by serobeah** [comment]
Sero

**Comment by angelXwind** [comment]
Update to the latest AppSync Unified version, many things in the code have changed that should have fixed the described issue.

輕更新到最新的AppSync Unified版，很多東西已經改變了，這個問題應該已經修好了。

Closing issue.

**Comment by Basputaek13** [comment]
Install
