### ISSUE TITLE
Package Breaking Error

### ISSUE THREAD

**Issue by xDarkNightPvPx** [angelXwind/AppSync#13]
Hey, Angel! If you're active, I guess you should read this. It's quite important.
I'm running an iPhone 5s on 8.1.3 and your AppSync unified package doesn't work at all!
It's kind of depressing, i've tried many AppSync packages and they just don't work. It could be a problem with my phone? I'm not 100% sure, that's why I'd like to contact an expert.
I try to use AppSync unified with AppCake and AppCake doesn't seem to pick it up at all... I'm unsure :/

**Comment by xDarkNightPvPx** [comment]
I've tried everything :/ maybe we could try a TeamViewer session?

**Comment by angelXwind** [comment]
What version of AppSync Unified have you tried installing?

**Comment by angelXwind** [comment]
Closed for inactivity.
