### ISSUE TITLE
iOS 10 support.

### ISSUE THREAD

**Issue by Fengson** [angelXwind/AppSync#14]
I'm afraid `AppSync` is not working anymore on `iOS 10`.
Are there any plans for an update?
Thank you for the hard work.

**Comment by TheNuclearCat** [comment]
https://twitter.com/angelXwind/status/813448445142953985

**Comment by Fengson** [comment]
Yeah, I've seen that. I was wondering about the developer's progress and if she could use any help.

**Comment by angelXwind** [comment]
@julioverne has added support for iOS 10 as of commit sha1 `1e3e6f1348a50608c3891c92918d55a40c71c22d`
