### ISSUE TITLE
AppSync stops working after a reboot on iOS 9.3.5

### ISSUE THREAD

**Issue by AaroniusLeonius** [angelXwind/AppSync#18]
After I install appsync, it works great but as soon as I reboot (and rejailbreak), it stops working. As soon as I reinstall, it starts working again.

**Comment by Cryptiiiic** [comment]
@angelXwind Why isn't net.angelxwind.asu_inject.plist or com.linusyang.appsync.plist included in the deb? This is probably the issue and why it doesn't work after rebooting.

**Comment by Cryptiiiic** [comment]
@AaroniusLeonius @angelXwind For some reason, the postinst script has to be run after every reboot for appsync to work. installd has to be inejcted with MobileSubstrate.dylib at every boot.

**Comment by angelXwind** [comment]
Huh, interesting. I'll take a look on my 9.3.5 device later, then. My best guess right now is that it's probably some implementation detail with how the Phœnix jailbreak restarts system services — it may differ from the method yalu102/jbme/other FastRecovery-esque jailbreaks uses.

**Comment by angelXwind** [comment]
Issue has been worked around as of latest commit `df11866df71b48933d8c50b1bafbffe2537fca70`, closing issue.
