### ISSUE TITLE
How am I supposed to install AppSync Unified? Had to reset my phone (Saïgon iOS 10.2.1)

### ISSUE THREAD

**Issue by MrDemocracy** [angelXwind/AppSync#19]
The first time I tried to install AppSync Unified on my iPhone 6S, my device went into a boot loop while trying to respring the device.
I had to reset my phone using Find my IPhone, to recover my phone again. 
After that, everything got f***ed... Cydia wouldn't update sources, or let me download anything anything at all. I had to sideload iFile and install OpenSSH to "fix" Cydia. Now it at least works, but I still get some signature errors, and something about "DepCompareOp".
I have tried to run Cydia Eraser, but I only get ```http-osx.cpp:131 Could not connect to the server.```
After I had to reset my iPhone with Find my iPhone, I am also unable to install Apple File Conduit "2".
I did a second attempt at installing AppSync, but this time all my System and Cydia-apps disappeared from the springboard, so I had to SSH to my iPhone and delete AppSync using terminal.
Installing AppSync Unified on my 6S has messed up my Jailbreak. 
If this is a known problem, why can't there be a "<10.2" dependency on the Cydia install page?
I don't have any shsh2 blobs of iOS 10.2.1, so I can't restore back to that firmware.
If you have any idea how I can fix the "http-osx.cpp:131 Could not connect to the server."-error in Cydia Eraser, it would be greatly appreciated. I have tried to contact Saurik about it, but haven't heard anything back from him.

**Comment by talanov** [comment]
Clear your hosts file.

You're blocking updates. 
(oscp.apple.com 127.0.0.1)

Please, close, when confirmed.

**Comment by MrDemocracy** [comment]
`oscp.apple.com` is not in my hosts file. 
Here's my hosts file:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
127.0.0.1 mesu.apple.com
127.0.0.1 radarsubmissions.apple.com
127.0.0.1 appldnld.apple.com
127.0.0.1 iphonesubmissions.apple.com
```

Btw, is AppSync Unified even safe to install on iOS 10.2.1?

**Comment by talanov** [comment]
You got mesu.apple.com, which is auto-update server too.
Clear your hosts file.

Yes, it's safe to use it.

**Comment by MrDemocracy** [comment]
By "clear", do you mean delete the hosts file? And is this in order to solve the Cydia Eraser problem, or the issues with AppSync?
