### ISSUE TITLE
When I run code 'make',  I get these code

### ISSUE THREAD

**Issue by hogenjiang** [angelXwind/AppSync#20]
Makefile:8: /makefiles/common.mk: No such file or directory
Makefile:13: /aggregate.mk: No such file or directory
make: *** No rule to make target `/aggregate.mk'.  Stop.

**Comment by talanov** [comment]
Theos's not installed.

**Comment by hosjiu1702** [comment]
maybe someone will need in the future https://github.com/theos/theos/wiki/Installation-macOS.
Need to install **theos** - A cross-platform suite of tools for building and deploying software for iOS and other platforms.
