### ISSUE TITLE
Not working after reboot

### ISSUE THREAD

**Issue by halilaykent** [angelXwind/AppSync#22]
I am using AppSync on iOS 10.2 yalu jailbreak and the problem is every time I reboot the appsync needs reinstall to work. If i uninstall appsync appstore stops updating and downloading apps

**Comment by Grafovich** [comment]
Same here on iPhone 5 10.3.3 h3lix. Also Apple File Conduit 2 not working after reboot. I think think this problem has the same root.

**Comment by Kyogre** [comment]
Same problem on ipad 2017 (ios 10.3.3 doubleh3lix RC8). I have to reinstall Appsync every time after reboot to got it working.

**Comment by LiBoHanse** [comment]
same here ipad4,4 10.3.3 with doubleh3lix. afc2 and appsync have to be reinstalled on each reboot

**Comment by angelXwind** [comment]
Closing this as it's a really old issue and I haven't been able to reproduce this bug at all with the current AppSync Unified version (90.0).

Feel free to create a new issue if you still experience these issues, though.

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/
