### ISSUE TITLE
 I'm curious.

### ISSUE THREAD

**Issue by buzai** [angelXwind/AppSync#23]
First of all I'm just curious. I won't pirate the software. I learned from some articles that this plugin can be hook installer, so the program can run without the need of code signing. When I observe the source code, you create a signature guarantee program that can run. But for those charged app, some articles say that in order to remove the DRM protection, let the charging program run first, then export the program out of memory, so the program is unprotected. But how is this process done? I'm curious.

**Comment by lone-wolf-akela** [comment]
If I read your question correctly, what you are looking for is a "decryption tool" or "executable dumper". You can check https://github.com/KJCracks/Clutch .
