### ISSUE TITLE
appinst saying install successfully but no icon present on screen

### ISSUE THREAD

**Issue by liuxuan30** [angelXwind/AppSync#25]
Hi there,

Good work! But found bug that appinst saying install successfully but no icon present on screen.

JB: doubleH3lix + 10.3.3 iPhone 6S

Tried several ipas, sometimes it says installed successfully, however no app icon presents on screen. If I repeat the install command again, sometimes the app icon appear then.

Kind of bug here. Thanks

**Comment by angelXwind** [comment]
Try running `uicache` over SSH as `mobile`. It may also be the case that the IPA you are trying to install lacks the required `platform-application` entitlement.

**Comment by liuxuan30** [comment]
the normal ipa shouldn't need platform-application I suppose.

Anyway, uicache might help.
