### ISSUE TITLE
appinst .How to call the code through other processes?

### ISSUE THREAD

**Issue by lgq2015** [angelXwind/AppSync#26]
appinst .How to call the code through other processes?
 pid_t pid;
    int status;
    const char* args[] = {"appinst", "/var/mobile/Containers/Data/Application/78D6FEAA-E390-487C-9B95-1E4D135146FA/Documents/coinprincess.ipa", NULL};
    posix_spawn(&pid, "/usr/bin/appinst", NULL, NULL, (char* const*)args, NULL);
    waitpid(pid, &status, WEXITED);

This section of the code is invalid

**Comment by angelXwind** [comment]
…? I'm not sure what you're trying to ask here.

You may invoke the `appinst` binary through `posix_spawn()` or something similar, and it seems like you're already doing that…?
