### ISSUE TITLE
Boots into safemode after update Ios 10.3.3

### ISSUE THREAD

**Issue by nkujomiru** [angelXwind/AppSync#28]
After updating to the latest 24.0 version, every time I install an app it trows me into safe mode. 
Device is Iphone 5, Ios 10.3.3, H3lix jailbreak

**Comment by angelXwind** [comment]
Huh, do you have any crash logs or syslogs? (Collect them using CrashReporter or something along those lines.)

Does this still occur with 30.0? What were you trying to installing the app with? (Xcode, `appinst`, iFile, Filza, etc.)
