### ISSUE TITLE
Does not work on ios 11.3.1

### ISSUE THREAD

**Issue by TheWeirdDev** [angelXwind/AppSync#30]
Hi, Thanks for the great work. 

Unfortunately the tweak does not work on ios 11.3.1 (iPad Air 2). when i try to install an ipa using ideviceinstaller, it gives me the following error message:

Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe800801c: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ZCFaJB/extracted/Payload/Cesium.app : 0xe800801c (No code signature found.)

**Comment by xFahrenheightx** [comment]
Same here. Another error I've gotten.

**Comment by mmm286** [comment]
Same error

**Comment by xFahrenheightx** [comment]
I get this error when trying to install non-pirated apps.
