### ISSUE TITLE
New version trigger "debug mode" on App Store, iOS 11.2.5

### ISSUE THREAD

**Issue by windyboy1704** [angelXwind/AppSync#34]
After I installed version 30.0 of AppSync Unified on iOS 11.2.5, it triggered "debug mode" on App Store. My App Store now looks like this:
[https://i.imgur.com/bv9yn0p.png](https://i.imgur.com/bv9yn0p.png)
[https://i.imgur.com/OQoIxuF.png](https://i.imgur.com/OQoIxuF.png)
[https://i.imgur.com/zmjMK1X.png](https://i.imgur.com/zmjMK1X.png)
Can't do anything but to remove it or otherwise restart my device. I hope there will be an update for this bug.

**Comment by angelXwind** [comment]
If you disable all tweaks except AppSyncUnified (using something like iCleaner Pro), does this still occur? This feels more like a tweak conflict than anything else, as AppSync Unified doesn't touch the App Store at all…

Also, make sure you're installing the official version from my repo.

**Comment by windyboy1704** [comment]
The problem is now fixed, by upgrading KarenPref and KarenLocalizer. Now my App Store is working again without debug mode （╹◡╹）
Thank you for your response.
