### ISSUE TITLE
Cydia error "subprocess new pre-removal script returned error exit status 126 - NO SUGGESTIONS WORK

### ISSUE THREAD

**Issue by dafnsdkjfnkdjn** [angelXwind/AppSync#38]
I saw this post: https://github.com/angelXwind/AppSync/issues/32

I have appsync installed from your repo. Never got it from a pirate repo.

When trying to remote it and reinstall I get sub-process/usr/libecex/cydia/cydo returned an error code (1)

I logged into my phone with cyberduck and tried sending the commands one by one and it did nothing

Not sure how to change the bundle ID.

Any ideas on how to fix?

**Comment by angelXwind** [comment]
Considering the age of this issue, I… hope you don't still have this problem?

In any case, AppSync Unified 90.0 definitely shouldn't have these problems (never came up in my testing from iOS 5.1.1 〜 14.1), so… feel free create a new issue if it still happens on the latest version.

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/
