### ISSUE TITLE
error installing with Sileo

### ISSUE THREAD

**Issue by mmm286** [angelXwind/AppSync#43]
Hi,
I have error installing in Sileo:
dpkg:error processing archive /var/cache/apt/archives/net.agelxwind.appsyncunified_32.0_iphoneos-arm.deb (--unpack):
trying to overwrite '/Library/LaunchDaemons/net.agelxwind.asu_inject.plist', witch is also in packet cydia.net.angelxwind.appsyncunified 32.0
Errores were ecouentered while processing:
/var/cache/apt/archives/net.angelxwind.appsyncunified_32.0_iphoneos-arm.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by JEmlay** [comment]
Looks like you have a locked file (net.agelxwind.asu_inject.plist).  Maybe do a complete reboot then do nothing else but go into Sileo and try again?

If not then try to SSH into it and delete that file manually or change it's permissions to 777

**Comment by angelXwind** [comment]
This isn't an AppSync Unified issue. Rather, it's an issue having to do with you having a second version of AppSync Unified (misspelled as `net.agelxwind.appsyncunified`) installed from a third-party repository that is not mine.

Please uninstall the other version of AppSync Unified, then install the version from my repository.
