### ISSUE TITLE
Still not working for A12. Crashes safari after reboot.

### ISSUE THREAD

**Issue by Detr0x** [angelXwind/AppSync#44]
Not Working for A12 devices. iFunbox and iMazing both gives installation failure errors. Also crashes Safari after restarting device and after trying to install an unsigned app.

**Comment by JEmlay** [comment]
No issues with Safari here but nothing will install properly.  With the last version of ASU everything would go through the normal steps but then no app would exist on the system.  Now when trying to install with iFunBox I get - "ERR: Package installation failed (-402620388)" (seems to be a code signing error) and when I try to install with Filza it wont even start the install steps.  I get a spinning wheel then it just gives up.

**Comment by angelXwind** [comment]
Issue lied with Substitute and not with ASU, and was fixed on unc0ver devices. Version 48.0 now has full support for A12/arm64e on unc0ver (Chimera support will be added once their Substitute version is updated).
