### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by EMBEZZL3R** [angelXwind/AppSync#47]
Please extend compatibility to iOS 12.2

**Comment by NoTooth666** [comment]
Is that possible if so any chance of eta

**Comment by MasterGamingYT** [comment]
There is a modified control.deb, she can use that one instead

**Comment by Account826** [comment]
There gonna be a update for 12.1.3 users?

**Comment by angelXwind** [comment]
Closing as iOS 12.4 has been supported as of version 41.1-NoA12.
