### ISSUE TITLE
Problem with the makefiles - unable to make/compile

### ISSUE THREAD

**Issue by git4net** [angelXwind/AppSync#5]
Hi,
Hi, I've just followed the instructions of:
   git clone https://github.com/angelXwind/AppSync.git
   cd AppSync
   make
- and here is the problem, cause it won't compile with simple error of:
   Makefile:7: /makefiles/common.mk: No such file or directory
   Makefile:11: /aggregate.mk: No such file or directory
   make: *** No rule to make target `/aggregate.mk'.  Stop.
- while this is clear that the Makefile of yours has the reference at:
   LINE 7: include $(THEOS)/makefiles/common.mk
   LINE 11: include $(THEOS_MAKE_PATH)/aggregate.mk
- and there is no such env. variables defined anywhere in Makefile nor in the system.

Please advise, how to build the AppSync then?
Regards, G4N.

**Comment by angelXwind** [comment]
You seem to be trying to compile this on an iPad. It's untested, and unsupported.

If you want a binary release, just get it from http://cydia.angelxwind.net/
