### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by maksix666** [angelXwind/AppSync#54]
![5D046D68-A9DE-471E-9C64-53FA9EE04601](https://user-images.githubusercontent.com/55089994/67545825-3fde3300-f703-11e9-8d2c-c4c400d8ed03.png)
How fix it? what does mean this error?

Unc0ver 3.7.0~b3
iOS 12.4
iPhone 6

**Comment by angelXwind** [comment]
Issue has been fixed as of ASU 64.0.
