### ISSUE TITLE
Please add support for iOS 13.4.1

### ISSUE THREAD

**Issue by nguyennk308** [angelXwind/AppSync#59]
![6D2515F3-B100-4677-A972-2EAE81CF1E06](https://user-images.githubusercontent.com/63439234/78962987-22215080-7b20-11ea-87c4-6dc80a720005.png)

**Comment by angelXwind** [comment]
Please update to AppSync Unified 74.0 for iOS 13.4.1 support. https://www.reddit.com/r/jailbreak/comments/fzwgy7/update_appsync_unified_740_now_with_ios_1341/
