### ISSUE TITLE
Not working anymore on iOS 5.1.1

### ISSUE THREAD

**Issue by AlbertoZiliani** [angelXwind/AppSync#60]
I tried it to install my old ipas on my old iPad 1 but everytime i try to istall i got this:

2020-04-24 16:33:32.643 appinst[200:707] appinst (App Installer)
2020-04-24 16:33:32.649 appinst[200:707] Copyright (C) 2014-2019 Linus Yang, Karen/あけみ
2020-04-24 16:33:32.652 appinst[200:707] ** PLEASE DO NOT USE APPINST FOR PIRACY **
2020-04-24 16:33:32.907 appinst[200:707] -[__NSArrayM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0x1580d0
2020-04-24 16:33:32.913 appinst[200:707] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0x1580d0'
*** First throw call stack:
(0x358ca88f 0x334ee259 0x358cda9b 0x358cc915 0x35827650 0x7b6d1 0x7b2b4)
terminate called throwing an exceptionAbort trap: 6

**Comment by BrentDaMage** [comment]
I too am finding that attempting to run an unsigned binary with and without AppSync Unified produces the same result.

Aug 24 19:22:00 Brents-iPhone amfid[157] <Error>: unrecognized status -25293 from codesigning library
Aug 24 19:22:00 Brents-iPhone amfid[157] <Error>: /private/var/mobile/Applications/E023384A-B4D0-4748-9903-E39521380713/robloxmobile.app/robloxmobile not valid: 0xe8008001: An unknown error has occurred.
Aug 24 19:22:00 Brents-iPhone SpringBoard[55] <Warning>: Unable to obtain a task name port right for pid 156: (os/kern) failure
Aug 24 19:22:00 Brents-iPhone com.apple.launchd[1] (UIKitApplication:com.roblox.robloxmobile[0x7ba][156]) <Notice>: (UIKitApplication:com.roblox.robloxmobile[0x7ba]) Exited: Killed: 9
Aug 24 19:22:00 Brents-iPhone com.apple.launchd[1] (UIKitApplication:com.roblox.robloxmobile[0x7ba]) <Warning>: (UIKitApplication:com.roblox.robloxmobile[0x7ba]) Throttling respawn: Will start in 2147483647 seconds
Aug 24 19:22:00 Brents-iPhone SpringBoard[55] <Warning>: Application 'ROBLOX' exited abnormally with signal 9: Killed: 9

**Comment by angelXwind** [comment]
@AlbertoZiliani appinst (App Installer) 1.1.4 has been released, which fixes the above issue.

https://www.reddit.com/r/jailbreak/comments/lhosr6/update_appinst_app_installer_114_fixed_a_crash/

@BrentDaMage, your issue seems to lie with your IPA, rather than either AppSync Unified or `appinst`. Please do feel free to open a separate issue if you run into another bug, though!
