### ISSUE TITLE
[Repo][Dependency] Cydia Substrate is required but not included

### ISSUE THREAD

**Issue by parkerlreed** [angelXwind/AppSync#61]
Spent a good hour trying to diagnose AppSync not working. The Cydia package doesn't list Cydia Substrate as a dependency. 

This should be added to the deps.

Thanks

**Comment by angelXwind** [comment]
The… package definitely does list Cydia Substrate as a dependency.

https://github.com/angelXwind/AppSync/blob/master/control#L2

I think what might be happening here is that you may have discovered a deficiency with the dependency chain that's being used — can you tell me what iOS version, jailbreak, and device you're using?

**Comment by parkerlreed** [comment]
iOS 6.1.3, whatever coolbooter injects, iPad Mini 1G

**Comment by parkerlreed** [comment]
iPod Touch 3G 5.1.1 absinthe 2.0.4

Same behavior https://www.youtube.com/watch?v=3w5OBe1I5yU&feature=youtu.be

**Comment by angelXwind** [comment]
AppSync Unified 90.0 has been released, which fixes this issue.

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/
