### ISSUE TITLE
Not working with ideviceinstaller

### ISSUE THREAD

**Issue by ZonD80** [angelXwind/AppSync#64]
execute on Mac:
ideviceinstaller -I test.app

Uploading test.app package contents... DONE.
Installing 'bundle.id'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)
Install: InstallingEmbeddedProfile (30%)
Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008018: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.AOFH1i/extracted/test.app

Tested on iOS 13.4.1 Jailbroken with unc0ver.

**Comment by demhademha** [comment]
Ideviceinstaller requires your ipa is signed.

**Comment by ZonD80** [comment]
Application verification is preformed on device, so appsync misses this method of installation. Somehow it works only for OTA installations via itms-services or manually via file manager. This is wrong. I guess it should work for every type of installation.

**Comment by angelXwind** [comment]
AppSync Unified 90.0 has been released, which fixes this issue.

I was able to use `ideviceinstaller` to install IPAs on iOS 5.1.1, 6.1.6, 7.1.2, 8.4.1, 9.0.2, 9.3.3, 10.2.1, 11.3.1, 12.4, 13.5, and 14.1.

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/
