### ISSUE TITLE
iPhone 5c (32bit) iOS 10.3.3 h3lix RC6, cannot install ipas without asu_inject, installed ipas are expired betas, cannot be started

### ISSUE THREAD

**Issue by Kethen** [angelXwind/AppSync#65]
With https://core.telegram.org/reproducible-builds and https://get.videolan.org/vlc-iOS/3.2.9/

using version 80 from your repo, thanks for maintaining everything up there

works on iPhone 6 12.4.8 checkra1n 1.0.1, injects correctly with substrate 0.9.7107, apps installs and starts but should the beta yellow dot be expected?

does't inject on iPhone 5c 10.3.3 h3lix-rc6, tried substrate 0.9.6301 and 0.9.7107

appinst and ideviceinstaller fails without running asu_inject first

Installation works with appinst and ideviceinstaller after running asu_inject, but both telegram and vlc are labeled as expired betas and would not launch

Inspecting installd with [gdb built by pancake](https://cydia.radare.org/pool/main/g/gdb/), AppSyncUnified is not loaded before asu_inject, once injected:

```
94 AppSyncUnified.dylib             - 0x3b6000          dyld Y Y /private/var/db/stash/_.7YQdzI/DynamicLibraries/AppSyncUnified.dylib at 0x3b6000 (offset 0x3b6000)
```
substrate loads BrowserDefault and PreferenceLoader to their respective targets properly using their bplist targetting packageids, while patych has failed to inject itself info installd and lsd as well, using this plist. 

```
Katharines-iPhone:~ root# cat /Library/MobileSubstrate/DynamicLibraries/patcyh.plist 
Filter = {
    Executables = ("lsd", "installd");
    Mode = "Any";
};
```
Perhaps substrate cannot target executable names anymore on iOS 10.3.3?

**Comment by Kethen** [comment]
other than running asu_inject, restarting installd also gets AppSync
```
Katharines-iPhone:~ root# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.mobile.installd.plist 
Katharines-iPhone:~ root# /bin/launchctl load /System/Library/LaunchDaemons/com.apple.mobile.installd.plist
```
However ipas installed with appinst are still expired betas (iPhone 5c)
![IMG_0001](https://user-images.githubusercontent.com/22017945/90103740-97728b80-dd75-11ea-99ba-808267d66460.PNG)

On the iPhone 6, apps can be launched, but a beta/testflight dot is also present
I don't mind it being there but it this behaviour expected?
![IMG_0005](https://user-images.githubusercontent.com/22017945/90103815-ba9d3b00-dd75-11ea-90df-2543d34f9f39.PNG)

**Comment by angelXwind** [comment]
AppSync Unified 90.0 now bypasses FrontBoard's signature verification functionality, which _should_ fix the issue you experience here.

Can you please update and see if this bug still happens?

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/
