### ISSUE TITLE
Not working with iOS 14

### ISSUE THREAD

**Issue by marcushallett** [angelXwind/AppSync#66]
Obviously the AppSync package hasn't been updated for iOS 14.

I did compile it, bumping the version in the control file without making any other changes to the source code. It _seems_ to have failed. I'm getting the "application is missing the application-identifier entitlement" error. I attempted the install using Filza.

In one instance, I had previously compiled the same application and it successfully installed under iOS 13.5. I tried with multiple applications with the same result on iPadOS 14.

As I only have one Apple device, I am incapable of replicating the problem on other devices.

**Comment by marcushallett** [comment]
Also getting a verification error when attempting debugging using Xcode.

**Comment by angelXwind** [comment]
AppSync Unified 90.0 has been released, which has full iOS 14 support.

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/
