### ISSUE TITLE
Fakesigned apps seem to crash using Odyssey/libhooker.

### ISSUE THREAD

**Issue by CrafterPika** [angelXwind/AppSync#68]
Not sure if i am the only one that who does have this issue.
But apps which are fakeisgned seem to crash on Odyssey/LibHooker

But on the other side if you sign the iPA with an revoked enterprise cert and install them with asu they open perfectly fine.

Would be happy if you can take a look at this problem.

**Comment by makejohn** [comment]
I got the same issue, the app that I installed before switched to "Libhooker" workes fine, even after I switched to "libhooker", they still work, You just can't install new "ipa" file

**Comment by angelXwind** [comment]
As far as I can tell, this isn't… actually a bug with AppSync Unified, but rather with Odyssey/libhooker.

The only thing AppSync Unified really does is allow you to _install_ apps. It doesn't really do anything as far as _running_ them goes.
