### ISSUE TITLE
"The executable contains an invalid signature." on xCode 6.3.2 with iOS 8.3

### ISSUE THREAD

**Issue by atanasbozhkov** [angelXwind/AppSync#7]
I installed the latest version of AppSync Unified today on my iPad Mini (iOS 8.3).
I followed all the steps (in these two guides - [Karen](http://angelxwind.net/?page/how2asu), [SO](http://stackoverflow.com/questions/26822962/bypass-code-signing-with-xcode-6)) in order to disable code signing on xCode 6.3.2. 

However - when I try to build my app and run it on the device I get - "The executable contains an invalid signature.". 

I jailbroke my device using the TaiG jailbreak (which was surprisingly buggy)
I tried restarting the device and re-installing AppSync, but to no avail. 
Interestingly enough I tried to get a free app's IPA and sync it through iTunes - but the app gets rejected. 
This leads me to believe that the problem might lie with the iPad (jailbreak or AppSync issue)

Any ideas how I can try to debug this?

**Comment by Alsher** [comment]
I have a similar issue, though the wording is a bit different. With Xcode 6.3.2, iOS 8.3, an iPhone 6 and AppSync Unified 5.5.1-1, whenever I try to run a project on a device, I get an "App installation failed. The application could not be verified." error. I have double-checked the tutorial and everything, but it does not seem to work. The same Xcode/iOSOpenDev setup has been working fine on iOs 8.1.2.

**Comment by gl00my** [comment]
Have same issue. Cant run my app build with xcode 6. Here is ipa: http://downloads.sourceforge.net/project/instead/instead/2.2.3/INSTEAD-2.2.3.ipa

Hope it helps. Works fine with jb 8.1

**Comment by atanasbozhkov** [comment]
I re-insatlled AppSync and I managed to sync the free CNN app through iTunes, but xCode is still failing to run the app on the device, because of the code signature. Is there any way for us to provide more debug info? @angelXwind

**Comment by tosbaha** [comment]
Same issue with iPhone 6

**Comment by corv89** [comment]
Also getting "App installation failed. The application could not be verified." with Xcode 6.3.2 as well as 6.4, AppSync Unified 5.5.1-1

**Comment by atanasbozhkov** [comment]
Has anyone tried it on iOS8.4?

**Comment by AzerTyQsdF** [comment]
Same issue iOS8.3 JB ==> Xcode 6.3 6.4 7.0. ==> iPhone 5C / 6+
                    iOS8.4 JB ==> Xcode 6.4 7.0 ==> iPhone 5C / 6+

**Comment by AzerTyQsdF** [comment]
it works fine before yesterday and some Cydia package update.

**Comment by AzerTyQsdF** [comment]
Taig 2.3.0 dont resolve issue. iPhone 5C / 6+

**Comment by manaf95** [comment]
For anyone who still has this issue, I was able to find the solution after hours of searching, which is to add the key "application-identifier" to the Entitlements.plist, with this string value: $(AppIdentifierPrefix)$(CFBundleIdentifier)
Apparently Xcode (6.4) and iOS (8.4) require an application-identifier tag in order to install the application.

**Comment by corv89** [comment]
Thank you @manaf95! Your fix works.

**Comment by atanasbozhkov** [comment]
@manaf95 Is that on 8.3? On 8.4 I am getting an xCode error: "ad hoc code signing not allowed with SDK 'iOS 8.4' ". Have Apple Removed that?

**Comment by AzerTyQsdF** [comment]
Thank you a lot. Everything work :dancers:

**Comment by manaf95** [comment]
You're welcome guys 😃

**Comment by angelXwind** [comment]
Refer to my reddit post for an updated `asu_pid.entitlements` file that serves as a workaround for this bug introduced in iOS 8.4: https://www.reddit.com/r/jailbreak/comments/3cssgx/update_updated_asu_pidentitlements_file_for/
