### ISSUE TITLE
Vui lòng cập nhật lên iOS14

### ISSUE THREAD

**Issue by zxq2233** [angelXwind/AppSync#70]
IOS tương thích mới nhất vẫn là 13.7.
Vui lòng cập nhật lên iOS 14.1 mới nhất hoặc ít nhất là cập nhật lên 14.

**Comment by angelXwind** [comment]
AppSync Unified 90.0 has been released, which has full iOS 14 support.

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/
