### ISSUE TITLE
Firmware depending problem in iOS 13.7.0

### ISSUE THREAD

**Issue by op06072** [angelXwind/AppSync#71]
![B4010CAB-DDF6-4788-953B-F83CEF4B4C78](https://user-images.githubusercontent.com/60420877/104163598-03970f80-543a-11eb-8f2b-c28560a5ef33.jpeg)
My iPad Pro’s firmware version is 13.7.0 but I couldn’t install your tweak because it said that it has depending problem in firmware version. So I edited firmware version to 13.7 then I can install this tweak. Could you fix it?

**Comment by angelXwind** [comment]
AppSync Unified 90.0 has been released, which fixes this issue.
